[package]
name = "mlar-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
mlar-rust = { path = ".." }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"

[[test]]
name = "2d_mesh"
path = "tests/2d_mesh/main.rs"

[[example]]
name = "inspect_arch"
path = "examples/declarative/inspect_arch.rs"
