[package]
name = "mlar-syntax-sugar"
version = "0.1.0"
edition = "2024"

[dependencies]
mlar-rust = { path = ".." }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"

[[test]]
name = "2d_mesh"
path = "tests/2d_mesh/main.rs"

[[example]]
name = "inspect_arch"
path = "examples/declarative/inspect_arch.rs"

[[example]]
name = "imperative_dual_noc_mesh"
path = "examples/imperative/dual_noc_mesh.rs"

[[example]]
name = "imperative_cache_hierarchy"
path = "examples/imperative/cache_hierarchy.rs"

[[example]]
name = "imperative_shared_link_mesh"
path = "examples/imperative/shared_link_mesh.rs"
